import { writeFileSync } from 'fs';
const BT = String.fromCharCode(96);
const SQ = String.fromCharCode(39);
const lines = [];
const a = (s) => lines.push(s);
a('<!DOCTYPE html>');
a('<html lang="en">');
a('<head>');
a('  <meta charset="UTF-8">');
a('  <meta name="viewport" content="width=device-width, initial-scale=1.0">');
a('  <title>Physics 2 Study Bot \u2014 Exam 2</title>');
a('  <style>');
a('    /* \u2500\u2500 RESET & BASE \u2500\u2500 */');
a('    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }');
a('    :root {');
a('      --bg: #0f1117;');
a('      --surface: #1a1d27;');
a('      --surface2: #23263a;');
a('      --border: #2e3250;');
a('      --accent: #6c7aff;');
a('      --accent2: #a78bfa;');
a('      --green: #34d399;');
a('      --red: #f87171;');
a('      --yellow: #fbbf24;');
a('      --text: #e2e8f0;');
a('      --text-dim: #94a3b8;');
a('      --radius: 12px;');
a('      --shadow: 0 4px 24px rgba(0,0,0,0.4);');
a('    }');
a('    html, body { height: 100%; }');
a('    body {');
a('      background: var(--bg);');
a('      color: var(--text);');
a("      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;");
a('      font-size: 16px;');
a('      line-height: 1.6;');
a('    }');
a('');
a('    /* \u2500\u2500 LAYOUT \u2500\u2500 */');
a('    #app { min-height: 100vh; display: flex; flex-direction: column; }');
a('    header {');
a('      background: var(--surface);');
a('      border-bottom: 1px solid var(--border);');
a('      padding: 0 24px;');
a('      display: flex;');
a('      align-items: center;');
a('      justify-content: space-between;');
a('      height: 60px;');
a('      position: sticky; top: 0; z-index: 100;');
a('    }');
a('    header h1 { font-size: 1rem; font-weight: 600; color: var(--accent); }');
a('    header h1 span { color: var(--text-dim); font-weight: 400; }');
a('    main { flex: 1; padding: 32px 24px; max-width: 800px; margin: 0 auto; width: 100%; }');
a('');
